<?php
/**
 * @file
 * Code for the RS Beliana Sync UI feature.
 */

include_once 'rs_beliana_sync_ui.features.inc';

/**
 * Implements hook_permission().
 */
function rs_beliana_sync_ui_permission() {
  return [
    'administer beliana' => [
      'title' => t('Administer Beliana'),
      'description' => t('Access all Beliana configuration pages'),
    ],
  ];
}

/**
 * Implements hook_menu().
 */
function rs_beliana_sync_ui_menu() {
  $menu_items = [];
  $menu_items['admin/config/services/beliana-sync'] = [
    'title' => t('Synchronisaton settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['rs_beliana_sync_ui_sync_settings_form'],
    'access arguments' => ['administer beliana'],
    'file' => 'rs_beliana_sync_ui.admin.inc',
  ];
  return $menu_items;
}

/**
 * Implements hook_action_info().
 */
function rs_beliana_sync_ui_action_info() {
  return [
    'rs_beliana_sync_ui_sync' => [
      'type' => 'entity',
      'label' => t('Publikovať do webovej verzie'),
      'configurable' => FALSE,
      'triggers' => ['any'],
      'behavior' => ['create_property'],
      'vbo_configurable' => FALSE,
      'pass rows' => TRUE,
    ],
  ];
}

/**
 * Callback for `rs_beliana_sync_ui_sync` action.
 *
 * Note: This should be never called, because we are overriding submit action.
 *
 * {@inheritdoc}
 */
function rs_beliana_sync_ui_sync(&$node, $context) {
  beliana_sync_sync($node, $context);
}

/**
 * Implements hook_form_alter().
 */
function rs_beliana_sync_ui_form_views_form_sync_to_web_page_alter(&$form, &$form_state) {
  if ($form_state['step'] === 'views_bulk_operations_confirm_form') {
    $form['actions']['submit']['#submit'] = ['rs_beliana_sync_ui_prepare_queue'];
  }
}

function rs_beliana_sync_ui_prepare_queue($form, &$form_state) {
  $source = $form_state['selection'];
  beliana_sync_prepare_queue($source);
}


/**
 * Implements hook_form_alter().
 */
function rs_beliana_sync_ui_form_alter(&$form, array $form_state, $form_id) {
  if (in_array($form_id, ['heslo_node_form', 'importovane_heslo_node_form'])) {
    if ($form['#node']->workbench_moderation['current']->state === 'na_zalomenie') {
      $form['actions']['sync'] = [
        '#type' => 'submit',
        '#access' => TRUE,
        '#value' => 'Publikovať vo webovej verzii',
        '#weight' => 150,
        '#submit' => [
          'rs_beliana_sync_ui_node_form_sync',
        ],
      ];
    }
  }
}

function rs_beliana_sync_ui_node_form_sync($form, &$form_state) {
  $source = [$form_state['values']['nid']];
  beliana_sync_prepare_queue($source);
}

/**
 * Implements hook_views_data().
 */
function rs_beliana_sync_ui_views_data() {
  $data = [];
  $data['beliana_sync'] = [
    'table' => [
      'group' => 'Beliana sync',
      'provider' => 'beliana_sync',
      'join' => [
        'node' => [
          'left_field' => 'nid',
          'field' => 'local',
        ],
        'node_revision' => [
          'left_field' => 'nid',
          'field' => 'local',
        ],
      ],
    ],
    'updated' => [
      'title' => t('The Unix timestamp of last sync.'),
      'help' => t('The Unix timestamp of last sync.'),
      'field' => [
        'id' => 'date',
        'handler' => 'views_handler_field_date',
      ],
      'filter' => [
        'id' => 'date',
        'handler' => 'views_handler_filter_date',
      ],
    ],
  ];

  return $data;
}