<?php
/**
 * @file
 * Code for the RS Beliana Sync UI feature.
 */

include_once 'rs_beliana_sync_ui.features.inc';

/**
 * Implements hook_permission().
 */
function rs_beliana_sync_ui_permission() {
  return [
    'administer beliana' => [
      'title' => t('Administer Beliana'),
      'description' => t('Access all Beliana configuration pages'),
    ],
  ];
}

/**
 * Implements hook_menu().
 */
function rs_beliana_sync_ui_menu() {
  $menu_items = [];
  $menu_items['admin/config/services/beliana-sync'] = [
    'title' => t('Synchronisaton settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['rs_beliana_sync_ui_sync_settings_form'],
    'access arguments' => ['administer beliana'],
    'file' => 'rs_beliana_sync_ui.admin.inc',
  ];
  return $menu_items;
}

/**
 * Implements hook_action_info().
 */
function rs_beliana_sync_ui_action_info() {
  return [
    'rs_beliana_sync_ui_sync' => [
      'type' => 'entity',
      'label' => t('Publish to web version'),
      'configurable' => FALSE,
      'triggers' => ['any'],
      'behavior' => ['create_property'],
      'vbo_configurable' => FALSE,
      'pass rows' => TRUE,
    ],
  ];
}

/**
 * Callback for `rs_beliana_sync_ui_sync` action.
 *
 * Note: This should be never called, because we are overriding submit action.
 *
 * @inheritdoc
 */
function rs_beliana_sync_ui_sync(&$node, $context) {
  beliana_sync_sync($node, $context);
}

/**
 * Implements hook_form_alter().
 */
function rs_beliana_sync_ui_form_views_form_publish_to_web_page_alter(&$form, &$form_state) {
  if ($form_state['step'] === 'views_bulk_operations_confirm_form') {
    $form['actions']['submit']['#submit'] = ['beliana_sync_prepare_queue'];
  }
}