<?php
/**
* @file
* adds a formatter for text fields that creates a facebook button
* https://www.metaltoad.com/blog/drupal-7-tutorial-creating-custom-formatters-field-api
*
*/

/**
* Implements hook_entity_info_alter().
*/
function liteformatter_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['lite_display'] = array(
    'label' => t('LITE display'),
    'custom settings' => TRUE,
  );
}

/**
* Implements hook_field_formatter_info().
*/
function liteformatter_field_formatter_info() {
  return array(
    'liteformatter_formatter' => array( //Machine name of the formatter
      'label' => t('LITE formatter'),
      'field types' => array('text_long'), //This will only be available to text fields
    ),
  );
}

/**
* Implements hook_field_formatter_view().
*/
function liteformatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  global $base_url;
  $ckeditor_js=$base_url."/".drupal_get_path("module","liteformatter").'/ckeditor/ckeditor.js';
  $element = array(); // Initialize the var
  // load ckeditor installed in the module. We assume LITE is installed in its plugins directory
  // these do not work
  //drupal_add_js(drupal_get_path("module","liteformatter").'/ckeditor/ckeditor.js');
  //drupal_add_js($ckeditor_js);
  $ckeditor_script='<script type="text/javascript" src="'.$ckeditor_js.'"></script>';
  //dpm($ckeditor_script);
  // this works
  $ckeditor_script='<script type="text/javascript" src="'.$ckeditor_js.'"></script>';
  $litescript="
<script>
	CKEDITOR.on( 'instanceCreated', function( event ) {
		var editor = event.editor, element = editor.element;
		editor.on( 'configLoaded', function() {
		  editor.config.extraPlugins = 'lite,wordcount,notification';
			showParagraphs: false,
		  editor.config.removePlugins = 'find,flash,font,pastefromword,horizontalrule,scayt' +
				'forms,iframe,image,newpage,removeformat,' +
				'smiley,specialchar,stylescombo,templates';
	          editor.config.removeButtons = 'HorizontalRule,Anchor,Unlink,Undo,Redo,Copy,Paste,Cut,Strike,Underline,PasteText,SpellChecker,NumberedList,BulletedList,Indent,Outdent,Format,Blockquote,Scayt';
		  editor.config.wordcount = {
			showParagraphs: false,
			showCharCount: true,
			countSpacesAsChars: true
		  };
		});
		editor.config.readOnly = true;
		editor.config.title = false;
	});
</script>";
  // the Show/Hide button
  $butt0='<button onclick="show_changes()" style="float:right;">Skryť/zobraziť zmeny</button><br/><br/>';
  $butt1="
<script>
function show_changes() {
    var text0 = document.getElementById('asdfg0');
    var text1 = document.getElementById('asdfg1');
    if (text0.style.display === 'none') {
        text0.style.display = 'block';
        text1.style.display = 'none';
    } else {
        text0.style.display = 'none';
        text1.style.display = 'block';
    }
};
</script>";
  $cc="<script>show_changes();</script>"; // call in order to hide one of the divs
  foreach ($items as $delta => $item) { 
    $output = _text_sanitize($instance, $langcode, $item, 'value');
    // render the text twice in different divs to switch between them
    $element[$delta] = array('#markup' => $ckeditor_script.$butt0.$butt1.$litescript.'<div id="asdfg0" contentEditable="false">'.$output.'</div>'.'<div id="asdfg1" contentEditable="true">'.$output.'</div>'.$cc);
  }
  return $element;
}
# vim: ai ts=2 sts=2 et sw=2 ft=php
