name: beliana.rs
recipe: drupal7
config:
  php: 7.4
  via: apache
  webroot: docroot
  database: mariadb:10.6
  drush: ^8
  xdebug: true
services:
  appserver:
#    scanner: false
    config:
      php: .lando/php.ini
  database:
    overrides:
      image: mariadb:10.6
      command: docker-entrypoint.sh mariadbd
      environment:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
proxy:
  appserver:
    - rs.beliana.lndo.site
    - webrs.beliana.lndo.site
