<?php
# vim: ai ts=2 sts=2 et sw=2 ft=php

/**
 * @file
 * Beliana sync main file.
 */

use GuzzleHttp\Client;

/**
 * Implements hook_menu().
 */
function beliana_sync_menu() {
  return [
    'sync-test' => [
      'page callback' => 'drupal_get_form',
      'page arguments' => ['beliana_sync_test_form'],
      'access arguments' => ['access content'],
    ],
  ];
}

/**
 * Implements hook_node_insert().
 *
 * We are extracting links from `Heslo` nodes.
 *
 * {@inheritdoc}
 */
function beliana_sync_node_insert($node) {
  if (in_array($node->type, ['heslo', 'importovane_heslo'])) {
    // Extract links.
    _beliana_sync_process_links($node);
  }
}

/**
 * Implements hook_node_update().
 *
 * We are extracting links from `Heslo` nodes.
 *
 * {@inheritdoc}
 */
function beliana_sync_node_update($node) {
  # do not execute in the case of workbench moderation state transitions
  # execute only on node saving
  # on node creation $node->workbench_moderation does not exist
  if (isset($node->workbench_moderation_state_new)  and 
        isset($node->workbench_moderation) and 
        $node->workbench_moderation['current']->state != $node->workbench_moderation_state_new) {
    return;
  }
  if (in_array($node->type, ['heslo', 'importovane_heslo'])) {
    // Remove links to old node.
    db_delete('beliana_links')
      ->condition('origin', $node->nid)
      ->execute();
    // Extract links.
    _beliana_sync_process_links($node);
  }
}

/**
 * Extract links from node and insert them into beliana_links table.
 *
 * @param $nid
 */
function _beliana_sync_process_links($node, $replace = FALSE) {
  // Extract links from field_text_hesla.
  $nid = $node->nid;
  $text = $node->field_text_hesla[LANGUAGE_NONE][0]['value'];
  // do not continue if text is empty
  if ( $text === "" ) return;
  $internalErrorsState = libxml_use_internal_errors(true); 
  $dom = new \DOMDocument();
  $dom->loadHTML(mb_convert_encoding($text, 'HTML-ENTITIES', 'UTF-8'));

  // handle errors locally
  $errors = libxml_get_errors();
  if ($errors) {
    # clear errors and restore error loging status
    foreach ($errors as $error) {
      html_error($node, $error, "Chyba HTML syntaxe (links)"); 
    }
    libxml_clear_errors();
    libxml_use_internal_errors($internalErrorsState);   
    # return unchanged text
    return null;
  }
  # clear errors and restore error loging status
  libxml_clear_errors();
  libxml_use_internal_errors($internalErrorsState); 

  /** @var \DOMElement[] $links */
  $links = $dom->getElementsByTagName('a');
  if (!empty($links)) {
    for ($i = $links->length - 1; $i >= 0; $i--) {
      $item = $links->item($i);
      $target = $item->getAttribute('href');
      if (!url_is_external($target)) {
        // Get rid of leading slash.
        if ($target[0] === '/') {
          $target = substr($target, 1);
        }
        // Get non-alias path, so we can get nid from it.
        $path = drupal_get_normal_path($target);
        $path_elements = explode('/', $path);
        // If alias belong to node, then insert record into beliana_links table.
        if ($path_elements[0] === 'node' && is_numeric($path_elements[1]) && !$replace) {
          $link = db_select('beliana_links', 'l')
            ->fields('l', ['origin'])
            ->condition('origin', $nid)
            ->condition('target', $path_elements[1])
            ->execute()
            ->fetchCol(0);
          // We insert new item only if it already doesn't exist.
          if (empty($link)) {
            db_insert('beliana_links')
              ->fields([
                'origin' => $nid,
                'target' => $path_elements[1],
              ])
              ->execute();
          }
        }

        if ($replace) {
          $remote_id = db_select('beliana_sync', 's')
            ->fields('s', ['remote'])
            ->condition('local', $path_elements[1])
            ->execute()
            ->fetchCol(0);
          if (!empty($remote_id)) {
            // If was synced, then replace href to remote site.
            $remote_id = reset($remote_id);
            $item->setAttribute('href', '/node/' . $remote_id);
          }
          else {
            // If not synced, then remove link completely.
            $lnkText = $item->textContent;
            $newTxtNode = $dom->createTextNode($lnkText);
            $item->parentNode->replaceChild($newTxtNode, $item);
          }
        }
      }
    }
  }

  if ($replace) {
    $fragment = '';
    foreach ($dom->getElementsByTagName('body')->item(0)->childNodes as $node) {
      $fragment .= $dom->saveHtml($node);
    }
    return $fragment;
  }
}

// display error message (illustration)
function il_error($node, $ilu_node, $msg, $category) {
  if ($node->type === 'ilustracia'){
    watchdog($category, 'Chyba v ilustrácii "@ilu_title": ' . $msg, [
      '@ilu_title' => $ilu_node->title,
    ], WATCHDOG_NOTICE);
    $msg = 'Chyba v ilustrácii <strong><a href="/' . $ilu_node->path['source'] .'">' . $ilu_node->title . '</a></strong>: ' . $msg . '.';
    drupal_set_message($msg, 'error');
  } else {
    watchdog($category, 'Chyba v hesle "@title": ilustrácia "@ilu_title:" ' . $msg, [
      '@title' => $node->title,
      '@ilu_title' => $ilu_node->title,
    ], WATCHDOG_NOTICE);
    $msg = 'Chyba v hesle <a href ="/' . $node->path['source'] . '">' . $node->title . '</a>: ilustrácia <strong><a href="/' . $ilu_node->path['source'] .'">' . $ilu_node->title . '</a></strong>: ' . $msg . '.';
    drupal_set_message($msg, 'error');
  }
}

// display error message (article)
function art_error($node, $msg, $category) {
  watchdog($category, 'Chyba v hesle "@title" ' . $msg, [
    '@title' => $node->title,
  ], WATCHDOG_NOTICE);
  $msg = 'Chyba v hesle <a href ="/' . $node->path['source'] . '">' . $node->title . '</a>: ' . $msg . '.';
  drupal_set_message($msg, 'error');
}

// prepare and display error message in the case of html syntax error
function html_error($node, $error, $shortmsg)
{
  $msg = $shortmsg .": ". $error->message . "(" . "riadok " . $error->line . ", znak " . $error->column . ")";
  art_error($node, $msg, 'htmlerror');
}

// eventual fixes in article text 
// nonbreakable space: " "
function modify_body_text($text)
{
  // remove alternative text
  $text = preg_replace('/(*UTF8)▶[kK][^◀]*◀/', '', $text);
  $text = preg_replace('/(*UTF8)▶[wW]([^◀]*)◀/', '\1', $text);

  // arrow ➔ for both web and print
  $text = str_replace("➔","→",$text);
  // arrow ⬈ only for print
  $text = str_replace(" ⬈ "," ",$text);
  $text = str_replace(" ⬈"," ",$text);
  $text = str_replace("⬈ "," ",$text);
  $text = str_replace(" "," ",$text);	// remove nonbreakable spaces
  // multiple spaces 
  $text = preg_replace('/(  +)/', ' ', $text);
  // &nbsp within numbers
  $text = preg_replace( '/([0-9]) ([0-9])/', "$1&nbsp;$2", $text);
  $text = preg_replace( '/([0-9]) · ([0-9])/', "$1&nbsp;·&nbsp;$2", $text);
  $text = preg_replace( '/([0-9]) x ([0-9])/', "$1&nbsp;x&nbsp;$2", $text);
  $text = preg_replace( '/([0-9]) × ([0-9])/', "$1&nbsp;×&nbsp;$2", $text);
  // &nbsp with Slovak single letter words
  $text = preg_replace( '/ ([ikosuvzKOSUVZ]) /', " $1&nbsp;", $text);
  // &nbsp with numbers and physical units
  $text = preg_replace( '/([0-9]) ([th%glm][ <,.;])/', "$1&nbsp;$2", $text);
  $text = preg_replace( '/([0-9]) ‰/', "$1&nbsp;‰", $text);
  $text = preg_replace( '/([0-9]) ([cnμmk][glm][ <,.;])/', "$1&nbsp;$2", $text);
  $text = preg_replace( '/([0-9]) μ([gm][ <,.;])/', "$1&nbsp;μ$2", $text);
  $text = preg_replace( '/([0-9]) (°[CF])/', "$1&nbsp;$2", $text);
  $text = preg_replace( '/(sup>) ([gs][ ,.;] )/', "$1&nbsp;$2", $text);
  $text = preg_replace( '/([0-9]) ([kM]eV)/', "$1&nbsp;$2", $text);
  // remove alignment (ignored anyway)
  //<th class="rtecenter" colspan="9">
  //<th class="rteleft" colspan="3">
  $text = str_replace( ' class="rtecenter"', '', $text);
  $text = str_replace( ' class="rteleft"', '', $text);
  
  return _beliana_sync_clean_tags($text);
}

function beliana_sync_sync($nid, &$context) {
  $skip = FALSE;
  // Make sure to only initialize the results the first time.
  if (!isset($context['results']['success'])) {
    $context['results']['messages'] = [];
    $context['results']['success'] = $context['results']['error'] = 0;
  }
  // Calculate Authorization header.
  $login = variable_get('beliana_web_login');
  $pass = variable_get('beliana_password_login');
  $auth_header = 'Basic ' . base64_encode($login . ':' . $pass);

  // Create client object.
  $client = new Client([
    'base_uri' => variable_get('beliana_web_uri'),
    'headers' => [
      'Content-Type' => 'application/json',
      'Accept' => 'application/json',
      'Authorization' => $auth_header,
    ],
    'query' => ['_format' => 'json'],
  ]);
  $generic_node = node_load($nid);
  $node = workbench_moderation_node_current_load($generic_node);
  $illustrations = [];	// list of illustrations to be published on web
  $skip = FALSE;
  
  // _check_links defined in beliana/beliana.module
  if (!_check_links($node)) {
    $skip = TRUE;
  }
  // check article text
  // are LITE changes still present?
  $text_hesla = $node->field_text_hesla[LANGUAGE_NONE][0]['value'];
  if (strpos($text_hesla,"ice-ins") or strpos($text_hesla, "ice-del")){
    art_error($node, 'v texte sú uložené LITE zmeny', 'sync');
    $skip = TRUE;
  }
  if (!_check_alternative_text_markers($node, $text_hesla, "v hesle")) {
    $skip = TRUE;
  }
  // are LITE changes still present in table?
  if (isset($node->field_table[LANGUAGE_NONE][0])) {
    $text_table = $node->field_table[LANGUAGE_NONE][0]['value'];
    if (strpos($text_table,"ice-ins") or strpos($text_table, "ice-del")){
      art_error($node, 'v tabuľke sú uložené LITE zmeny', 'sync');
      $skip = TRUE;
    }
    if (!_check_alternative_text_markers($node, $text_table, "v tabuľke pre geografické údaje hesla")) {
      $skip = TRUE;
    }
  }

  if (isset($node->field_ilustracia[LANGUAGE_NONE]) ) {
    foreach ($node->field_ilustracia[LANGUAGE_NONE] as $illustration) {
      $ilu_generic_node = node_load($illustration['target_id']);
      $ilu_node = workbench_moderation_node_current_load($ilu_generic_node);

      //if (!_check_field_pouzit($node, $ilu_node, 'sync')) {
        //$skip = TRUE;
      //}

      // add illustration to the list, ignore it, if it is not intended for web
      if (il_display_on_web($ilu_node)) {
        $illustration_data = _check_illustration_web($node, $ilu_node, 'sync');
        if (is_null($illustration_data)) {
          $skip = TRUE;
        } else {
          $illustrations[] = $illustration_data;
        }
      }
    }
  }

  # remove links to not yet published articles
  $body = _beliana_sync_process_links($node, true);
  # if failed owing to html syntax error
  if (!$body) $skip = true;

  // if something went wrong, return now
  if($skip) {
    $context['results']['error']++;
    return;
  }

  $body = modify_body_text($body);

  // publish everything now
    $dates = [];
    if (isset($node->field_datum[LANGUAGE_NONE])) {
      foreach ($node->field_datum['und'] as $item) {
        $only_date = date('Y-m-d', strtotime($item['value']));
        $dates[] = $only_date;
      }
    }

    // form object to be sent over.
    $remote_node_object = [
      'title' => $node->title,
      'body' => $body,
      'images' => $illustrations,
      'sort' => $node->field_na_zoradenie['und'][0]['value'],
      'dates' => $dates,
      'info_published' => _extract_published_info($node)._extract_updated_info($node),
      //'category' => ["geografia;afrika","geografia;európa","fyzika"],
      //'category' => ["asdf;ghjk;pqr"],
      //'category' => ["asdf1;ghjk;pqr"],
      'category' => _extract_category_info($node),
    ];
    // add table, if the field is defined and if there really is a table in it
    if (isset($node->field_table[LANGUAGE_NONE]) and !(strpos($node->field_table[LANGUAGE_NONE][0]['value'], 'table') === False)) {
      $remote_node_object['table'] = array(
         modify_body_text($node->field_table[LANGUAGE_NONE][0]['value']),
         (isset($node->field_table_weight[LANGUAGE_NONE])) ?  $node->field_table_weight[LANGUAGE_NONE][0]['value'] : 0
      );
    } else {
      // delete the table on the web side, if it exists there
      $remote_node_object['table'] = array(Null, 0);
    }

    // Use POST for creating new items and PATCH for updating existing items.
    $remote_id = db_select('beliana_sync', 's')
      ->fields('s', ['remote'])
      ->condition('local', $nid)
      ->execute()
      ->fetchCol(0);
    // if not empty and not equal to '0' 
    // '0' have postponed pure link articles with unresolved link, not yet transfered to web, but already published
    if (!empty($remote_id) && $remote_id[0] != '0') {
      $remote_id = reset($remote_id);
      $response = $client->request('PATCH', '/rs/api/' . $remote_id, ['body' => json_encode($remote_node_object)]);
      db_update('beliana_sync')
        ->fields(['updated' => time()])
        ->condition('local', $nid)
        ->execute();
      //if ($response->getStatuscode() !== 200)
        //dpm($response->getStatusCode(),"PATCH failed");
    } else {
      // postpone transfer of articles which are pure link articles with unresolved link
      // list them in the beliana_sync table, so that they will be transferred to web automatically 
      // as soon as the target is published

      // first delete synchronization info for the earlier postponed articles
      if (!empty($remote_id) && $remote_id[0] == '0') {
        db_delete('beliana_sync')
          ->condition('local', $nid)
          ->execute();
      }	

      // the articles to be postponed contain neither the '—' character, nor the '<a >' tag
      if (!(strpos($body, '—') == false && strpos($body, '<a ') == false)) {
        $response = $client->request('POST', '/rs/api', ['body' => json_encode($remote_node_object)]);
        // If new node was created on remote, insert its nid to beliana_sync table.
        if ($response->getStatusCode() === 201) {
          $remote_id = (int) json_decode($response->getBody());
          db_insert('beliana_sync')
            ->fields([
              'local' => $nid,
              'remote' => $remote_id,
              'updated' => time()
            ])
            ->execute();
        //} else {
        //dpm($response->getStatusCode(),"POST failed");
        }
      } else {
          // insert the postponed articles into the table of synchronized articles, but with id '0'
          db_insert('beliana_sync')
            ->fields([
              'local' => $nid,
              'remote' => 0,
              'updated' => time()
            ])
            ->execute();
      }
    }
    // Change workbench status for node and attached illustrations.
    workbench_moderation_moderate($node, 'publikovane_na_webe');
    foreach ($illustrations as $illustration) {
      $ilu_generic_node = node_load($illustration['nid']);
      $ilu_node = workbench_moderation_node_current_load($ilu_generic_node);
      workbench_moderation_moderate($ilu_node, 'ilustracia_na_webe');
    }
    watchdog('sync', 'Heslo "@title" bolo úspešne prenesené.', [
      '@title' => $node->title,
    ], WATCHDOG_INFO);
    $context['results']['success']++;

    // save the date of first publication to web here
    if (!isset($node->field_datum_prveho_zverejnenia[LANGUAGE_NONE][0]['value'])) {
      $node->field_datum_prveho_zverejnenia[LANGUAGE_NONE][0]['value'] = date("Y/m/d - H:i");
      node_save($node);
    }
}

// check if illustration should go to web
function il_display_on_web(&$ilu_node) 
{
  if (!isset($ilu_node->field_pouzit[LANGUAGE_NONE])) 
    return false;
  foreach ($ilu_node->field_pouzit[LANGUAGE_NONE] as $value) {
    if ($value['value'] === 'Zobrazit_na_webe') {
      return true;
    }
  }
  return false;
}

// check if illustration should be printed
function il_print(&$ilu_node) 
{
  if (!isset($ilu_node->field_pouzit[LANGUAGE_NONE])) 
    return false;
  foreach ($ilu_node->field_pouzit[LANGUAGE_NONE] as $value) {
    if ($value['value'] === 'Zaradit_do_tlace') {
      return true;
    }
  }
  return false;
}

function get_order($source, $source_links) {
  $dest = [];
  $i = 0;
  $limit = pow(sizeof($source), 2) + 1;
  $moved = [];
  while (!empty($source)) {
    $current = array_shift($source);
    $links = $source_links[$current];
    $i++;
    if ($i % $limit === 0) {
      $dest[] = $current;
      $moved[] = $current;
      continue;
    }
    if (!empty($links)) {
      $found = FALSE;
      foreach ($links as $link) {
        if (in_array($link, $source)) {
          $found = TRUE;
          $source[] = $current;
          break;
        }
      }
      if (!$found) {
        $dest[] = $current;
      }
    }
    else {
      $dest[] = $current;
    }
  }

  $dest = array_merge($dest, $moved);
  return $dest;
}

function beliana_sync_prepare_queue($source) {
  $source_links = [];
  $back_links = [];
  $back_links_links = [];
  $operations = [];
  foreach ($source as $item) {
    $links = db_select('beliana_links', 'l')
      ->fields('l', ['target'])
      ->condition('origin', $item)
      ->execute()
      ->fetchCol(0);
    $source_links[$item] = $links;

    $item_back_links_query = db_select('beliana_links', 'l');
    $item_back_links_query->join('beliana_sync', 's', 'l.origin=s.local');
    $item_back_links = $item_back_links_query->fields('l', ['origin'])
      ->isNotNull('s.local')
      ->condition('l.target', $item)
      ->distinct()
      ->execute()
      ->fetchCol(0);

    foreach ($item_back_links as $item_back_link) {
      if (!isset($back_links_links[$item_back_link])) {
        $back_links_local_links = db_select('beliana_links', 'l')
          ->fields('l', ['target'])
          ->condition('origin', $item_back_link)
          ->execute()
          ->fetchCol(0);
        $back_links_links[$item_back_link] = $back_links_local_links;
      }
    }

    $back_links = array_merge($back_links, $item_back_links);
  }
  $back_links = array_unique($back_links);
  $sync_queue = get_order($source, $source_links);
  $back_links_queue = get_order($back_links, $back_links_links);
  $sync_queue = array_merge($sync_queue, $back_links_queue);

  // synchronize just the unique items from the queue
  foreach (array_unique($sync_queue) as $item) {
    $operations[] = [
      'beliana_sync_sync',
      [$item],
    ];
  }

  $batch = array(
    'title' => t('Publishing content to web version...'),
    'operations' => $operations,
    'finished' => 'beliana_sync_sync_finished',
    'init_message' => t('Publishing is starting ...'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('An error occurred during processing'),
  );

  batch_set($batch);
}

function beliana_sync_sync_finished($success, $results, $operations) {
  drupal_set_message('Synchronizácia bola ukončená - ' . $results['success'] . ' úspešne, ' . $results['error'] . ' - neúspešne');
  foreach ($results['messages'] as $message) {
    drupal_set_message($message, 'error');
  }
  return '';
}

function _extract_category_info($node) {
  $taglist = [];
  foreach($node->field_lexikalna_skupina["und"] as $ls) {
    $term = taxonomy_term_load($ls['tid']);
    $taglist[] = $term->field_taglist['und'][0]['value'];
  }
  return $taglist;
}

// select image in the order svg, png, jpg
function _extract_image(array $images) {
  foreach ($images as $image) {
    if (strpos($image['filemime'], 'svg')) {
      return file_create_url($image['uri']);
    }
  }
  foreach ($images as $image) {
    if (strpos($image['filemime'], 'png')) {
      return file_create_url($image['uri']);
    }
  }
  foreach ($images as $image) {
    if (strpos($image['filemime'], 'jpeg')) {
      return file_create_url($image['uri']);
    }
  }
  return NULL;
}

function _extract_license($node) {
  $formatted_license = '';
  $raw_license = $node->field_zdroj_ilustracie[LANGUAGE_NONE][0]['value'];
  //license names ('Creative Commons ...') must be exactly the same as in the 'Licencie' taxonomy in the web version 
  switch ($raw_license) {
    case 'Vlastná ilustrácia':
      $formatted_license = 'Creative Commons BY-SA';
      break;
    case 'Public domain':
      $formatted_license = 'Voľné dielo';
      break;
    case 'CC licencia':
      switch ($node->field_licencia1[LANGUAGE_NONE][0]['value']) {
      case 'CC BY-ND':
        $formatted_license = 'Creative Commons BY-ND';
        break;
      case 'CC BY-NC':
        $formatted_license = 'Creative Commons BY-NC';
        break;
      case 'CC BY-SA':
        $formatted_license = 'Creative Commons BY-SA';
        break;
      case 'CC BY-NC-ND':
        $formatted_license = 'Creative Commons BY-NC-ND';
        break;
      case 'CC BY-NC-SA':
        $formatted_license = 'Creative Commons BY-NC-SA';
        break;
      case 'CC BY':
        $formatted_license = 'Creative Commons BY';
        break;
      case 'IVL':
        $formatted_license = 'Iná verejná licencia';
        break;
      case 'CC0':
        $formatted_license = 'Creative Commons CC0';
        break;
      }
      break;
    case 'Získané na základe zmluvy':
    case 'Muzeálny objekt':
    case 'Autorské dielo':
    case 'Iná licencia':
      $formatted_license = 'Všetky práva vyhradené';
      break;
  }
  return $formatted_license;
}

/*
*  extract information regarding the date of first publishing.
*  Different for the 'Importovane heslo' and 'Heslo' types  
*/
function _extract_published_info($node) {
  $label = 'Zverejnené';
  
  // Set the publishing date according to the article name
  // the key in the $bands array is a first string in the next band 
  $bands = array (
    "bell" => "$label v auguste 1999",
    "czzzz" => "$label v júli 2001",
    "eh" => "$label v máji 2003",
    "galb" => "$label v júli 2005",
    "his" => "$label vo februári 2008",
    "in" => "$label v apríli 2010",
    "kam" => "$label v novembri 2013",
    "koks" => "$label v marci 2017",
  );

  setlocale(LC_COLLATE, 'sk_SK.utf8');
  if ( $node->type ==  'importovane_heslo' ){
    // get name of article, specified in node->field_taxsubor 
    $vocabulary = taxonomy_vocabulary_machine_name_load('subory');
    $collections = taxonomy_get_tree($vocabulary->vid);
    foreach ($collections as $term) {
      if ($term->tid == $node->field_taxsubor['und'][0]['tid']) {
        $collection = $term->name;
        break;
      }
    }

    # get publication year info
    foreach ($bands as $key => $txt) {
      $publishedinfo = $txt;
      if (strcoll($collection, $key) < 0 ) {
	# $publishedinfo is not set for the first band
        #if (!isset($publishedinfo))
          #$publishedinfo = $txt;
        break;
      }
    }
  } else { // the Heslo type
    // if already published, the 'field_datum_prveho_zverejnenia' is set 
    // the field is set elsewhere, after a successfull transfer to web
    if (isset($node->field_datum_prveho_zverejnenia[LANGUAGE_NONE][0]['value'])) {
      $publishedinfo = " $label " .  _form_date2($node->field_datum_prveho_zverejnenia[LANGUAGE_NONE][0]['value']);
    } else {
      $publishedinfo = " $label " .  _form_date2(date("d.m.Y"));
    }
  }
  return $publishedinfo . ".";
}

function _extract_updated_info($node) {
  if (isset($node->field_datum_aktualizacie[LANGUAGE_NONE][0]['value'])) {
    return " Aktualizované " .  _form_date2($node->field_datum_aktualizacie[LANGUAGE_NONE][0]['value']) . ".";
  } else {
    return("");
  }
}

/*
 * replaces month abbrevoation with inflected full name in genitive 
 */
function _form_date2($utime) {
  setlocale(LC_TIME, 'sk_SK.utf8');
  $fdate = strftime("%e. %b %Y", strtotime($utime));
  $fdate = str_replace("jan","januára",$fdate);
  $fdate = str_replace("feb","februára",$fdate);
  $fdate = str_replace("mar","marca",$fdate);
  $fdate = str_replace("apr","apríla",$fdate);
  $fdate = str_replace("máj","mája",$fdate);
  $fdate = str_replace("jún","júna",$fdate);
  $fdate = str_replace("júl","júla",$fdate);
  $fdate = str_replace("aug","augusta",$fdate);
  $fdate = str_replace("sep","septembra",$fdate);
  $fdate = str_replace("okt","októbra",$fdate);
  $fdate = str_replace("nov","novembra",$fdate);
  $fdate = str_replace("dec","decembra",$fdate);
  return $fdate;
}

/*
 * replaces month abbrevoation with inflected full name in local with preposition 
 */
function _form_date6() {
  setlocale(LC_TIME, 'sk_SK.utf8');
  $fdate = strftime("%b %Y");
  $fdate = str_replace("jan","v januári",$fdate);
  $fdate = str_replace("feb","vo februári",$fdate);
  $fdate = str_replace("mar","v marci",$fdate);
  $fdate = str_replace("apr","v apríli",$fdate);
  $fdate = str_replace("máj","v máji",$fdate);
  $fdate = str_replace("jún","v júni",$fdate);
  $fdate = str_replace("júl","v júli",$fdate);
  $fdate = str_replace("aug","v auguste",$fdate);
  $fdate = str_replace("sep","v septembri",$fdate);
  $fdate = str_replace("okt","v októbri",$fdate);
  $fdate = str_replace("nov","v novembri",$fdate);
  $fdate = str_replace("dec","v decembri",$fdate);
  return $fdate;
}

/*
 * check correctness of an illustration
 * $category values:
 * 'sync': execute test only during synchronization to web
 * 'state change': execute test in general state change
 * 'state change ge': execute test on state change from graphics editor to editor 
 * return: illustration data or null
 */
function  _check_illustration_web(&$node, &$ilu_node, $category)
{
  $skip=false;
  // check illustration text
  $text_il = $ilu_node->field_popis[LANGUAGE_NONE][0]['value'];
  // are LITE changes still present?
  if (strpos($text_il,"ice-ins") or strpos($text_il, "ice-del")){
    il_error($node, $ilu_node, 'v texte sú uložené LITE zmeny', $category);
    $skip = TRUE;
  }
  $plen = strlen($ilu_node->field_popis['und'][0]['value'])>130;
  // not executed if field_pouzit is not set appropriately (i.e. illustration should not be displayed on web)
  // Check if illustration has image attached.
  if (!(isset($ilu_node->field_subor_ilustracie[LANGUAGE_NONE]) or isset($ilu_node->field_obrazok_odkaz[LANGUAGE_NONE]))) {
    il_error($node, $ilu_node, "v poli 'Súbory ilustrácie' nie je uložený súbor obrázka a nie je určený odkaz", $category);
    $skip = TRUE;
  }

  // we synchronize linked image, if it is specified
  if (isset($ilu_node->field_obrazok_odkaz[LANGUAGE_NONE])) {
    $image_url_web = $ilu_node->field_obrazok_odkaz[LANGUAGE_NONE][0]['value'];
  } elseif (isset($ilu_node->field_subor_ilustracie[LANGUAGE_NONE])) {
    $image_url_local = _extract_image($ilu_node->field_subor_ilustracie[LANGUAGE_NONE]);
    if (is_null($image_url_local)) {
      il_error($node, $ilu_node, " v poli 'Súbory ilustrácie' nie je uložený súbor vhodného typu (svg, png, jpg)", $category);
      $skip = TRUE;
    }
  }

  // Check if illustration is in correct WB status.
  if ($category == 'sync' and !in_array($ilu_node->workbench_moderation['current']->state, [
      'ilustracia_na_zverejnenie',
      'ilustracia_na_webe',
      'ilustracia_u_vyst_redaktora_5',
      ])) {
    il_error($node, $ilu_node, 'sa nenachádza v stave "Ilustrácia na zverejnenie"', $category);
    $skip = TRUE;
  }

  // Check if illustration has correct license.
  if ((!isset($ilu_node->field_zdroj_ilustracie['und']) || $ilu_node->field_zdroj_ilustracie['und'][0]['value'] === 'Zatiaľ neurčený')) {
    il_error($node, $ilu_node, 'nie je určený platný typ ilustrácie', $category);
    $skip = TRUE;
  } else {
    $license = _extract_license($ilu_node);
    if (empty($license)) {
      il_error($node, $ilu_node, 'nesprávne určený typ licencie', $category);
      $skip = TRUE;
    } else if ($category == "state change ge" and $license == 'Iná verejná licencia' and !isset($ilu_node['url_textu_licencie_l'])){
      il_error($node, $ilu_node, 'ak je zvolená "Iná verejná licencia", pole "URL textu licencie" musí byť vyplnené"', $category);
      $skip = TRUE;
    }
  } 

  // Check if alternative text is correct
  $atext = _beliana_remove_accents(preg_replace('/<[^>]*>/', '',  $ilu_node->field_popis[LANGUAGE_NONE][0]['value']));
  $plen = strlen($atext)>122;
  if (!isset($ilu_node->field_alternativny_text['und']) && $plen) {
    il_error($node, $ilu_node, 'popis je dlhší ako 120 znakov a nie je vložený Alternatívny text.', $category);
    $skip = TRUE;
  }

  // return if something failed
  if ($skip)  return null;

  // collect illustration data
  $ill_data = [
    'nid' => $ilu_node->nid,
    //'uri' => $image_url_local,
    'title' => $ilu_node->title,
    'description' => $ilu_node->field_popis[LANGUAGE_NONE][0]['value'],
    'license' => $license,
  ];
  //$ix = count($illustrations) - 1;	// index of the last item
  if( isset($image_url_local) )
    $ill_data['image_url_local'] = $image_url_local;
  if( isset($image_url_web) )
    $ill_data['image_url_web'] = $image_url_web;
  if( isset($ilu_node->field_meno_autora_diela[LANGUAGE_NONE]) )
    $ill_data['meno_autora_diela'] = $ilu_node->field_meno_autora_diela[LANGUAGE_NONE][0]['value'];
  if( isset($ilu_node->field_meno_autora_snimky_diela[LANGUAGE_NONE]) ) 
    $ill_data['meno_autora_snimky_diela'] = $ilu_node->field_meno_autora_snimky_diela[LANGUAGE_NONE][0]['value'];
  if( isset($ilu_node->field_nazov_diela[LANGUAGE_NONE]) ) 
    $ill_data['nazov_diela'] = $ilu_node->field_nazov_diela[LANGUAGE_NONE][0]['value'];
  if( $ilu_node->field_zdroj_ilustracie[LANGUAGE_NONE][0]['value'] == 'Vlastná ilustrácia' ) {
    $ill_data['institucia'] = "Encyklopedický ústav SAV";
  } else {  
    if( isset($ilu_node->field_institucia[LANGUAGE_NONE]) ) 
      $ill_data['institucia'] = $ilu_node->field_institucia[LANGUAGE_NONE][0]['value'];
  }
  if( isset($ilu_node->field_url_diela_l[LANGUAGE_NONE]) ) 
    $ill_data['url_diela_l'] = $ilu_node->field_url_diela_l[LANGUAGE_NONE][0]['url'];
  if( isset($ilu_node->field_url_autora_diela_l[LANGUAGE_NONE]) ) 
    $ill_data['url_autora_diela_l'] = $ilu_node->field_url_autora_diela_l[LANGUAGE_NONE][0]['url'];
  if( isset($ilu_node->field_url_textu_licencie_l[LANGUAGE_NONE]) ) 
    $ill_data['url_textu_licencie_l'] = $ilu_node->field_url_textu_licencie_l[LANGUAGE_NONE][0]['url'];

  if( isset($ilu_node->field_alternativny_text[LANGUAGE_NONE]) ) { 
    $ill_data['alternativny_text'] = $ilu_node->field_alternativny_text[LANGUAGE_NONE][0]['value'];
  } else {
    // remove eventual formatting (only strong and em are eventually still here), copy just 125 characters
    $atext = preg_replace('/<[^>]*>/', '',  $ilu_node->field_popis[LANGUAGE_NONE][0]['value']);
    $ill_data['alternativny_text'] = substr($atext, 0, 125);
  }
return $ill_data;
}

/*
 * if there are images, but 'field_pouzit' (use) is not set, break processing
 * this is a very rare situation
*/
function _check_field_pouzit(&$node, &$ilu_node, $category)
{
  $auxsub = isset($ilu_node->field_subor_ilustracie[LANGUAGE_NONE]);
  $auxobr = isset($ilu_node->field_obrazok_navrh_[LANGUAGE_NONE]);
  $auxodk = isset($ilu_node->field_obrazok_odkaz[LANGUAGE_NONE]);
  $auxpou = !isset($ilu_node->field_pouzit[LANGUAGE_NONE]);
  if(($auxsub or $auxobr or $auxodk) and $auxpou) {
    il_error($node, $ilu_node, 'nemá nastavený spôsob použitia', $category);
    return false;
  }
  return true;
}

// remove unnecessary and unwanted tags in synchronization
function _beliana_sync_clean_tags($text)
{

  $internalErrorsState = libxml_use_internal_errors(true); 
  $dom = new \DOMDocument();
  $dom->loadHTML(mb_convert_encoding($text, 'HTML-ENTITIES', 'UTF-8'));

  // handle errors locally
  $errors = libxml_get_errors();
  if ($errors) {
    # clear errors and restore error loging status
    foreach ($errors as $error) {
      html_error($node, $error, "Chyba HTML syntaxe (clean sync)"); 
    }
    libxml_clear_errors();
    libxml_use_internal_errors($internalErrorsState);   
    # return unchanged text
    return null;
  }
  # clear errors and restore error loging status
  libxml_clear_errors();
  libxml_use_internal_errors($internalErrorsState); 

  $xpath = new DOMXPath($dom);

  // remove tag attributes
  $cltags=array(
    array("a","style"),
    array("a","target"),
    array("td","style"),
    array("table","border"),
    array("table","cellspacing"),
    array("table","cellpadding"),
    array("table","style"),
    array("span","style"),
  );
  foreach ($cltags as $cltag) {
    $tagstring = "//".$cltag[0]."[@".$cltag[1]."]";
    foreach ($xpath->query($tagstring) as $tag) {
      $sNode = $tag->getAttributeNode( $cltag[1] );
      $tag->removeAttributeNode( $sNode );
    }
  }

  // remove tags completely: <ins>, <span>, ....
  $rmtags=array(
  '//ins[not(@*)]',
  '//span[not(@*)]',
  '//td/p',
  );
  foreach ($rmtags as $tag) {
  //_remove_node($xpath, $tag);
  // Move all tag node content to its parent node just before it.
  foreach ($xpath->query($tag) as $node) {
    while ($node->hasChildNodes()) {
      $child = $node->removeChild($node->firstChild);
      $node->parentNode->insertBefore($child, $node);
    }
    // Remove the tag node.
    $node->parentNode->removeChild($node);
    }
  }

  $fragment = '';
  foreach ($dom->getElementsByTagName('body')->item(0)->childNodes as $chnode) {
    $fragment .= $dom->saveHtml($chnode);
  }
  return $fragment;
}
