<?php
/**
 * @file
 * Code for the RS Beliana Workbench feature.
 */

include_once 'rs_beliana_workbench.features.inc';

/**
 * Implements hook_views_query_alter().
 *
 * We are are altering views generated query, so we can display
 * label of workbench states.
 *
 * @inheritdoc
 */
function beliana_workbench_views_query_alter(&$view, &$query) {
  if ('beliana' === $view->name) {
    $join = new views_join();
    $join->table = 'workbench_moderation_states';
    $join->field = 'name';
    $join->left_table = 'workbench_moderation_node_history';
    $join->left_field = 'from_state';
    $join->type = 'left';

    $query->add_relationship('workbench_moderation_states', $join, 'node');
    $query->add_field('workbench_moderation_states', 'label');
    $view->add_item($view->current_display, 'field', 'workbench_moderation_states', 'label');

  }
}