<?php

/**
 * @file
 * Code for the Redakčný systém Beliana Heslo feature.
 */
include_once 'rs_beliana_node_heslo.features.inc';

/**
 * Implement hook_menu()
 */
function rs_beliana_node_heslo_menu() {
  $items = array();

//  $items['node/%node/content'] = array(
//    'title' => t('Edit content'),
//    'type' => MENU_LOCAL_TASK,
//    'page callback' => 'drupal_get_form',
//    'access callback' => 'rs_beliana_node_heslo_content_access',
//    'page arguments' => array('rs_beliana_node_heslo_content_edit_form', 1),
//    'access arguments' => array(1),
//  );

  return $items;
}

/**
 * Function to get access for edit "heslo" content
 */
function rs_beliana_node_heslo_content_access($node) {
  if (in_array($node->type, array('heslo', 'importovane_heslo')) && (user_access('edit own ' . $node->type . ' content') || user_access('edit any ' . $node->type . ' content'))) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Function to edit "heslo" content only
 */
function rs_beliana_node_heslo_content_edit_form($form, &$form_state, $node) {
  module_load_include('inc', 'field_ui', 'field_ui.admin');

  $field = field_info_field('field_text_hesla');
  $instance = field_info_instance('node', 'field_text_hesla', $node->type);

  $form += field_ui_default_value_widget($field, $instance, $form, $form_state);
  $form['field_text_hesla'][LANGUAGE_NONE][0]['#default_value'] = $node->field_text_hesla[LANGUAGE_NONE][0]['value'];

  $form['actions'] = array(
    '#type' => 'actions'
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

/**
 * Submit function for edit "heslo" content form
 */
function rs_beliana_node_heslo_content_edit_form_submit(&$form, &$form_state) {
  $node = $form_state['build_info']['args'][0];
  $node->field_text_hesla = $form_state['values']['field_text_hesla'];

  node_save($node);
  drupal_goto('node/' . $node->nid);
}

/**
 * Implements hook_node_postinsert().
 */
function rs_beliana_node_heslo_node_postinsert($node) {
  switch ($node->type) {
    case 'heslo':
      if (empty($node->field_remote_id[LANGUAGE_NONE][0]['value'])) {
        if ($response = beliana_api_rest_create_node($node, 'rsw', "Nové heslo:")) {
          $node->field_remote_id[LANGUAGE_NONE][0]['value'] = $response->nid;
          node_save($node);
        }
      }
      break;
    case 'ilustracia':
      if (empty($node->field_remote_id[LANGUAGE_NONE][0]['value'])) {
        if ($response = beliana_api_rest_create_node($node, 'rsw', "Nová ilustrácia:")) {
          $node->field_remote_id[LANGUAGE_NONE][0]['value'] = $response->nid;
          node_save($node);
        }
      }
      break;
  }
}

/**
 * Implements hook_cron().
 */
function rs_beliana_node_heslo_cron() {
  // select nodes with missing "lexikalna skupina" in workbench access and send notification
  $results = db_query("SELECT n.nid FROM {node} n NATURAL LEFT JOIN {workbench_access_node} wa WHERE wa.nid IS NULL AND n.type = (:type)", [':type' => 'heslo'])->fetchAll();

  if (!empty($results)) {
    $params = ['nodes' => []];

    foreach ($results as $result) {
      if ($node = node_load($result->nid)) {
        $params['nodes'][] = $node;
      }
    }

    if (!empty($params['nodes'])) {
      drupal_mail('rs_beliana_node_heslo', 'missing_node_in_view', 'encytsra@savba.sk', language_default(), $params);
    }
  }
}

/**
 * Implements hook_mail().
 */
function rs_beliana_node_heslo_mail($key, &$message, $params) {
  switch ($key) {
    case 'missing_node_in_view':
      $message['subject'] = 'ENCB-156: Heslo asi zmizlo z views';

      foreach ($params['nodes'] as $node) {
        $message['body'][] = t('@nid @date @url - heslo treba otvorit a opatovne ulozit;', [
          '@nid' => $node->nid,
          '@date' => date('Y/m/d H:i:s', $node->created),
          '@url' => url('node/' . $node->nid, ['absolute' => TRUE]),
        ]);
      }
      break;
  }
}
