<?php
/**
 * @file
 * Module file for beliana module.
 */

/**
 * Implements hook_menu().
 *
 * @inheritdoc
 */
function beliana_menu() {
  $items = array();
  $items['admin/users-list'] = array(
    'title' => 'Users list',
    'page callback' => 'beliana_users_list',
    'access arguments' => array('bypass node access'),
  );

  $items['admin/group-list'] = array(
    'title' => 'Group list',
    'page callback' => 'beliana_group_list',
    'access arguments' => array('bypass node access'),
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 *
 * @inheritdoc
 */
function beliana_menu_alter(&$items) {
  if (isset($items['admin/workbench/sections'])) {
    unset($items['admin/workbench/sections']);
  }

  if (isset($items['node/%node/draft'])) {
    unset($items['node/%node/draft']);
  }

  if (isset($items['node/%node/revisions'])) {
    unset($items['node/%node/revisions']);
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * @inheritdoc
 */
function beliana_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if (isset($data['tabs'][0]['output'])) {
    foreach ($data['tabs'][0]['output'] as $i => $tab) {
      if (in_array($tab['#link']['path'], array(
        'admin/tasks',
        'admin/index',
      ))) {
        unset($data['tabs'][0]['output'][$i]);
      }
    }
  }
}


/**
 * Menu callback for `admin/group-list` path.
 *
 * We are printing users grouped by terms assigned to users.
 *
 * @return string
 *   HTML output of users.
 */
function beliana_group_list() {
  $users = entity_load('user');
  $terms = taxonomy_get_tree(2);
  $output = '';
  foreach ($terms as $term) {
    $output .= '<h3>' . $term->name . '</h3>';
    $output .= '<ul>';
    foreach ($users as $user) {
      if (isset($user->workbench_access[$term->tid])) {
        $output .= '<li>' . $user->name . '</li>';
      }
    }
    $output .= '</ul><br><br>';
  }
  return $output;
}

/**
 * Menu callback for `admin/users-list` path.
 *
 * We are printing users with group assigned to users.
 *
 * @return string
 *   HTML output of all users with their groups.
 */
function beliana_users_list() {
  $users = entity_load('user');
  $terms = taxonomy_get_tree(2);
  $output = '';
  foreach ($users as $user) {
    $output .= '<div>';
    $output .= '<h3>' . $user->name . '</h3>';
    $output .= '<ul>';
    foreach ($terms as $t) {
      if (isset($user->workbench_access[$t->tid])) {
        $output .= '<li>' . $t->name . '</li>';
      }
    }
    $output .= '</ul><br><br></div>';
  }
  return $output;
}

/**
 * Implements hook_action_info().
 *
 * @inheritdoc
 */
function beliana_action_info() {
  return array(
    'beliana_merge' => array(
      'type' => 'entity',
      'label' => t('Merge'),
      'configurable' => FALSE,
      'triggers' => array('any'),
      'behavior' => array('create_property'),
      'vbo_configurable' => FALSE,
      'pass rows' => TRUE,
    ),
    'beliana_assign_author' => array(
      'type' => 'entity',
      'label' => t('Určiť autora a priradiť autorovi'),
      'configurable' => TRUE,
      'triggers' => array('any'),
      'behavior' => array('create_property'),
      'vbo_configurable' => FALSE,
      'pass rows' => TRUE,
    ),
    'beliana_assign_corrector' => array(
      'type' => 'entity',
      'label' => t('Určiť autora a priradiť redaktorovi'),
      'configurable' => TRUE,
      'triggers' => array('any'),
      'behavior' => array('create_property'),
      'vbo_configurable' => FALSE,
      'pass rows' => TRUE,
    ),
  );
}

/**
 * Configuration form for `beliana_assign_author` action.
 *
 * @inheritdoc
 */
function beliana_assign_author_form($form, &$form_state) {
  return _beliana_assign_user_form();
}

/**
 * Validation for `beliana_assign_author_form`.
 *
 * @inheritdoc
 */
function beliana_assign_author_validate($form, &$form_state) {
  _beliana_validate_assign_user_form($form_state);
}

/**
 * Submit function for `beliana_assign_author_form`.
 *
 * @inheritdoc
 */
function beliana_assign_author_submit($form, $form_state) {
  return _beliana_submit_assign_user_form($form_state, 'u_autora');

}

/**
 * Callback for `beliana_assign_author` action.
 *
 * Assigns selected user as node author and
 * changes workflow status to `u_autora`.
 *
 * @inheritdoc
 */
function beliana_assign_author(&$node, $context) {
  _beliana_assign_user($node, $context);
}

/**
 * Configuration form for `beliana_assign_corrector` action.
 *
 * @inheritdoc
 */
function beliana_assign_corrector_form($form, &$form_state) {
  return _beliana_assign_user_form();
}

/**
 * Validation for `beliana_assign_corrector_form` form.
 *
 * @inheritdoc
 */
function beliana_assign_corrector_validate($form, &$form_state) {
  _beliana_validate_assign_user_form($form_state);

}

/**
 * Submit function for for `beliana_assign_corrector_form` form.
 *
 * @inheritdoc
 */
function beliana_assign_corrector_submit($form, $form_state) {
  return _beliana_submit_assign_user_form($form_state, 'needs_review');
}

/**
 * Callback function for `beliana_assign_corrector` action.
 *
 * Assigns selected user as node author and
 * change workflow status to `needs_review`.
 *
 * @inheritdoc
 */
function beliana_assign_corrector(&$node, $context) {
  _beliana_assign_user($node, $context);
}

/**
 * Callback function for `beliana_merge` action.
 *
 * @inheritdoc
 *
 * @see beliana_action_info
 */
function beliana_merge(&$entity, $context = array()) {
  // If current entity is the first one,
  // create new entity `Heslo` and store its nid into session.
  if ($context['progress']['current'] === 1) {
    $master = new stdClass();
    $master->type = 'heslo';
    node_object_prepare($master);
    $master->title = $entity->title;
    $master->field_text_hesla = array(
      LANGUAGE_NONE => array(
        array(
          'value' => '',
          'format' => 'filtered_html',
        ),
      ),
    );
    $master->field_taxsubor = $entity->field_taxsubor;
    $master->language = 'sk';
    node_save($master);
    $_SESSION['master'] = $master->nid;
  }

  // Load master entity from session.
  $master = node_load($_SESSION['master']);

  // If master entity found, copy fields from current entity into it.
  if ($master != FALSE) {
    $master->field_text_hesla[LANGUAGE_NONE][0]['value'] .= $entity->field_text_hesla[LANGUAGE_NONE][0]['value'];

    if (!empty($entity->field_image)) {
      foreach ($entity->field_image[LANGUAGE_NONE] as $img) {
        $master->field_image[LANGUAGE_NONE][] = $img;
      }

      foreach ($entity->field_text_k_ilustraciam[LANGUAGE_NONE] as $text) {
        $master->field_text_k_ilustraciam[LANGUAGE_NONE][] = $text;
      }
    }
    $master->field_zlucene_z[LANGUAGE_NONE][]['target_id'] = $entity->nid;
    $master->field_autor_povodneho_textu[LANGUAGE_NONE][]['target_id'] = $entity->uid;


    foreach ($entity->field_lexikalna_skupina[LANGUAGE_NONE] as $ls) {
      $parents = taxonomy_get_parents_all($ls['tid']);
      foreach ($parents as $parent) {
        if (count(taxonomy_get_parents_all($parent->tid)) == 1) {
          $top_parent = $parent;
        }
      }

      $found = FALSE;
      foreach ($master->field_spravit_1_korekturu[LANGUAGE_NONE] as $tid) {
        if ($tid['tid'] === $top_parent->tid) {
          $found = TRUE;
        }
      }
      if (!$found) {
        $master->field_spravit_1_korekturu[LANGUAGE_NONE][]['tid'] = $top_parent->tid;
	//MS we want to preserve the original taxonomy values in further processing
        //MS $master->field_povodne_lexikalne_skupiny[LANGUAGE_NONE][]['tid'] = $top_parent->tid;
        $master->field_povodne_lexikalne_skupiny[LANGUAGE_NONE][]['tid'] = $ls;
      }
    }
    node_save($master);

    $entity->field_zlucene_do[LANGUAGE_NONE][0]['target_id'] = $_SESSION['master'];
    node_save($entity);
    workbench_moderation_moderate($entity, 'ukoncenezluene');
  }

  // If current entity is the last, make workflow transition.
  if ($context['progress']['current'] === $context['progress']['total']) {
    $master = node_load($_SESSION['master']);
    $term = array_shift(taxonomy_get_term_by_name('Zlúčené heslo', 'lexikalne_skupiny'));
    $master->field_lexikalna_skupina[LANGUAGE_NONE][]['tid'] = $term->tid;
    node_save($master);
    workbench_moderation_moderate($master, 'zlucene');
    $_SESSION['master'] = NULL;
  }
}

/**
 * Implements hook_node_presave().
 *
 * @inheritdoc
 */
function beliana_node_presave($node) {
  // Load user which is author of the node.
  $author = user_load($node->uid);
  setlocale(LC_COLLATE, 'sk_SK.utf8');

  // If field for ordering is empty, we need to fill in value for it.
  if ($node->field_na_zoradenie['und'][0]['value'] == '') {
    $transliterated = _belina_remove_accents($node->title);
    $transliterated = preg_replace('/[^a-zA-ZŠšČčŽž]/', '', $transliterated);
    $transliterated = strtolower($transliterated);
    $node->field_na_zoradenie['und'][0]['value'] = $transliterated;
  }
  else {
    $transliterated = $node->field_na_zoradenie['und'][0]['value'];
  }

  // Set taxonomy grop, because it can be changed by admin.
  $vocabulary = taxonomy_vocabulary_machine_name_load('subory');
  $terms = taxonomy_term_load_multiple(array(), array('vid' => $vocabulary->vid));

  foreach ($terms as $term) {
    $term_transliterated = _belina_remove_accents($term->name);
    $term_transliterated = strtolower($term_transliterated);
    $term_transliterated = preg_replace('/[^a-zA-ZŠšČčŽž]/', '', $term_transliterated);

    if (strcoll($term_transliterated, $transliterated) >= 0) {
      $node->field_taxsubor['und'][0]['tid'] = $term->tid;
      break;
    }
  }

  // New nodes don't have any state.
  if (isset($node->workbench_moderation['current']->state) && isset($node->workbench_moderation_state_new)) {
    if (($node->workbench_moderation['current']->state === 'na_jazykovu_korekturu'
      && $node->workbench_moderation_state_new === '1_korektura')
    ) {
      $node->field_lexikalna_skupina['und'][0] = array_shift($node->field_spravit_1_korekturu['und']);
    }

    if ($node->workbench_moderation['current']->state === '1_korektura'
      && $node->workbench_moderation_state_new === 'u_vyst_redaktora_3'
    ) {
      if (!empty($node->field_spravit_1_korekturu['und'])) {
        $node->workbench_moderation_state_new = '1_korektura';
        $node->field_lexikalna_skupina['und'][0] = array_shift($node->field_spravit_1_korekturu['und']);
      }
      else {
        $term = array_shift(taxonomy_get_term_by_name('Zlúčené heslo', 'lexikalne_skupiny'));
        $node->field_lexikalna_skupina['und'][0] = array('tid' => $term->tid);
      }
    }

    if ($node->workbench_moderation_state_new === '2_korekt_ra') {
      $term = array_shift(taxonomy_get_term_by_name('Zlúčené heslo', 'lexikalne_skupiny'));
      foreach ($node->field_lexikalna_skupina['und'] as $ls) {
        if ($ls['tid'] == $term->tid) {
          drupal_set_message('Ako lexikálnu skupinu zadajte meno redaktora!', 'error');
        }
      }
    }
  }

  // Editor has to change author from 'import' to something else.
  // If node is assigned to 'import', we need to forbid change of state.
  if ($author->name === 'import'
    && isset($node->workbench_moderation_state_new)
    && isset($node->workbench_moderation['current']->state)
    && $node->workbench_moderation['current']->state === 'zaradene'
    && in_array($node->workbench_moderation_state_new, array(
      'u_autora',
      'needs_review',
    ))
  ) {
    $node->workbench_moderation_state_new = 'zaradene';
    drupal_set_message($node->title . ': Pred zmenou stavu treba heslo priradiť autorovi.', 'error');
  }
}

/**
 * Implements hook_form_alter().
 *
 * @inheritdoc
 */
function beliana_form_alter(&$form, &$form_state, $form_id) {
  if ('workbench_moderation_moderate_form' === $form_id) {
    // If user is import and state is `zaradene`,
    // we remove option `u_autora` from possible next states.
    if ($form['node']['#value']->workbench_moderation['current']->state === 'zaradene'
      && $form['node']['#value']->uid == 719
    ) {
      foreach ($form['state']['#options'] as $k => $v) {
        if (in_array($k, array('needs_review', 'u_autora'))) {
          unset($form['state']['#options'][$k]);
        }
      }
    }

    // Add custom submit handler.
    $form['#submit'][] = 'beliana_workflow_reaction';
  }
}

/**
 * Callback function for `workbench_moderation_moderate_form` submit.
 *
 * @inheritdoc
 */
function beliana_workflow_reaction(&$form, &$form_state) {
  $values = $form_state['values'];
  // If is new, current state is empty.
  //MS modify field_lexikalna_skupina only for merged items, i.e. >field_zlucene_z is not empty
  if (isset($values['node']->workbench_moderation['current']->state) && count($values['node']->field_zlucene_z['und']) > 0) {
    if (($values['node']->workbench_moderation['current']->state === 'na_jazykovu_korekturu' && $values['state'] === '1_korektura')) {
      $values['node']->field_lexikalna_skupina['und'][0] = array_shift($values['node']->field_spravit_1_korekturu['und']);
    }

    if ($values['node']->workbench_moderation['current']->state === '1_korektura' && $values['state'] === 'u_vyst_redaktora_3') {
      if (!empty($values['node']->field_spravit_1_korekturu['und'])) {
        $values['node']->workbench_moderation_state_new = '1_korektura';
        $values['node']->field_lexikalna_skupina['und'][0] = array_shift($values['node']->field_spravit_1_korekturu['und']);
      }
      else {
        $values['node']->field_lexikalna_skupina = $values['node']->field_povodne_lexikalne_skupiny;
      }
    }

    if ($values['state'] === '2_korekt_ra') {
      if (count($values['node']->field_lexikalna_skupina['und']) != 1) {
        //MS drupal_set_message('Ako lexikálnu skupinu zadajte meno požadovaného redaktora.', 'error');
        drupal_set_message('Heslo je zlúčené a má viacero lexikálnych skupín. Pri odosielaní na 2. korektúru však heslo môže mať len jednu lexikálnu skupinu.', 'error');
        drupal_set_message('Lexikálne skupiny upravte, heslo uložte a potom odošlite na 2. korektúru ešte raz. Po návrate z 2. korektúry sa lexikálne skupiny vrátia do pôvodného stavu.', 'error');
        $values['node']->workbench_moderation_state_new = 'u_vyst_redaktora_3';
      }
    }

    if ($values['node']->workbench_moderation['current']->state === '2_korekt_ra' && $values['state'] === 'u_vyst_redaktora_3') {
      $values['node']->field_lexikalna_skupina = $values['node']->field_povodne_lexikalne_skupiny;
    }
    node_save($values['node']);
  }
}

/**
 * Helper function to get user autocomplete form.
 *
 * @return array
 *   Array with form element.
 */
function _beliana_assign_user_form() {
  $form = array();
  $form['user'] = array(
    '#type' => 'textfield',
    '#title' => t('Vyberte autora, ktorému chcete heslo priradiť'),
    '#required' => TRUE,
    '#autocomplete_path' => 'user/autocomplete',
  );
  return $form;
}


/**
 * Helper function for user autocomplete form validation.
 *
 * @param array $form_state
 *   Array with form values.
 */
function _beliana_validate_assign_user_form(&$form_state) {
  if (user_load_by_name($form_state['values']['user']) === FALSE) {
    form_set_error('user', t('You need to choose existing user'));
  }
}

/**
 * Helper function for processing user autocomplete form submit.
 *
 * @param array $form_state
 *   Array with form values.
 * @param string $state
 *   New status for node.
 *
 * @return array
 *   Keyed array with user nd status.
 */
function _beliana_submit_assign_user_form($form_state, $state) {
  $return = array();
  $return['user'] = $form_state['values']['user'];
  $return['status'] = $state;
  return $return;
}

/**
 * Helper function changing node author and workflow status.
 *
 * @param object $node
 *   Object of node.
 * @param array $context
 *   Array of context.
 *
 * @throws \Exception
 *
 * @return FALSE
 *   Return FALSE if assigning of the new group failed.
 */
function _beliana_assign_user(&$node, $context) {
  $user = user_load_by_name($context['user']);
  if ($user !== FALSE) {
    if (!isset($user->workbench_access[reset($node->workbench_access)])) {
      drupal_set_message($node->title . ' sa nepodarilo priradiť autorovi, pretože nemá zodpovedajúcu lexikálnu skupinu.', 'error');
      return FALSE;
    }
    $node->uid = $user->uid;
    node_save($node);
    workbench_moderation_moderate($node, $context['status']);
  }
}


/**
 * Helper function removing accents.
 *
 * @param string $text
 *   String we want to remove accents from.
 *
 * @return string
 *   String without accents.
 */
function _belina_remove_accents($text) {
  $trans = array(
    'À' => 'A',
    'Á' => 'A',
    'Â' => 'A',
    'Ã' => 'A',
    'Ä' => 'A',
    'Å' => 'A',
    'Ç' => 'C',
    'È' => 'E',
    'É' => 'E',
    'Ê' => 'E',
    'Ë' => 'E',
    'Ì' => 'I',
    'Í' => 'I',
    'Î' => 'I',
    'Ï' => 'I',
    'Ñ' => 'N',
    'Ò' => 'O',
    'Ó' => 'O',
    'Ô' => 'O',
    'Õ' => 'O',
    'Ö' => 'O',
    'Ø' => 'O',
    'Ù' => 'U',
    'Ú' => 'U',
    'Û' => 'U',
    'Ü' => 'U',
    'Ý' => 'Y',
    'à' => 'a',
    'á' => 'a',
    'â' => 'a',
    'ã' => 'a',
    'ä' => 'a',
    'å' => 'a',
    'ç' => 'c',
    'è' => 'e',
    'é' => 'e',
    'ê' => 'e',
    'ë' => 'e',
    'ì' => 'i',
    'í' => 'i',
    'î' => 'i',
    'ï' => 'i',
    'ñ' => 'n',
    'ò' => 'o',
    'ó' => 'o',
    'ô' => 'o',
    'õ' => 'o',
    'ö' => 'o',
    'ø' => 'o',
    'ù' => 'u',
    'ú' => 'u',
    'û' => 'u',
    'ü' => 'u',
    'ý' => 'y',
    'ÿ' => 'y',
    'Ā' => 'A',
    'ā' => 'a',
    'Ă' => 'A',
    'ă' => 'a',
    'Ą' => 'A',
    'ą' => 'a',
    'Ć' => 'C',
    'ć' => 'c',
    'Ĉ' => 'C',
    'ĉ' => 'c',
    'Ċ' => 'C',
    'ċ' => 'c',
    'Ď' => 'D',
    'ď' => 'd',
    'Đ' => 'D',
    'đ' => 'd',
    'Ē' => 'E',
    'ē' => 'e',
    'Ĕ' => 'E',
    'ĕ' => 'e',
    'Ė' => 'E',
    'ė' => 'e',
    'Ę' => 'E',
    'ę' => 'e',
    'Ě' => 'E',
    'ě' => 'e',
    'Ĝ' => 'G',
    'ĝ' => 'g',
    'Ğ' => 'G',
    'ğ' => 'g',
    'Ġ' => 'G',
    'ġ' => 'g',
    'Ģ' => 'G',
    'ģ' => 'g',
    'Ĥ' => 'H',
    'ĥ' => 'h',
    'Ħ' => 'H',
    'ħ' => 'h',
    'Ĩ' => 'I',
    'ĩ' => 'i',
    'Ī' => 'I',
    'ī' => 'i',
    'Ĭ' => 'I',
    'ĭ' => 'i',
    'Į' => 'I',
    'į' => 'i',
    'İ' => 'I',
    'ı' => 'i',
    'Ĵ' => 'J',
    'ĵ' => 'j',
    'Ķ' => 'K',
    'ķ' => 'k',
    'Ĺ' => 'L',
    'ĺ' => 'l',
    'Ļ' => 'L',
    'ļ' => 'l',
    'Ľ' => 'L',
    'ľ' => 'l',
    'Ŀ' => 'L',
    'ŀ' => 'l',
    'Ł' => 'L',
    'ł' => 'l',
    'Ń' => 'N',
    'ń' => 'n',
    'Ņ' => 'N',
    'ņ' => 'n',
    'Ň' => 'N',
    'ň' => 'n',
    'ŉ' => 'n',
    'Ō' => 'O',
    'ō' => 'o',
    'Ŏ' => 'O',
    'ŏ' => 'o',
    'Ő' => 'O',
    'ő' => 'o',
    'Ŕ' => 'R',
    'ŕ' => 'r',
    'Ŗ' => 'R',
    'ŗ' => 'r',
    'Ř' => 'R',
    'ř' => 'r',
    'Ś' => 'S',
    'ś' => 's',
    'Ŝ' => 'S',
    'ŝ' => 's',
    'Ş' => 'S',
    'ş' => 's',
    'Ţ' => 'T',
    'ţ' => 't',
    'Ť' => 'T',
    'ť' => 't',
    'Ŧ' => 'T',
    'ŧ' => 't',
    'Ũ' => 'U',
    'ũ' => 'u',
    'Ū' => 'U',
    'ū' => 'u',
    'Ŭ' => 'U',
    'ŭ' => 'u',
    'Ů' => 'U',
    'ů' => 'u',
    'Ű' => 'U',
    'ű' => 'u',
    'Ų' => 'U',
    'ų' => 'u',
    'Ŵ' => 'W',
    'ŵ' => 'w',
    'Ŷ' => 'Y',
    'ŷ' => 'y',
    'Ÿ' => 'Y',
    'Ź' => 'Z',
    'ź' => 'z',
    'Ż' => 'Z',
    'ż' => 'z',
    'ƀ' => 'b',
    'Ɓ' => 'B',
    'Ƃ' => 'B',
    'ƃ' => 'b',
    'Ƈ' => 'C',
    'ƈ' => 'c',
    'Ɗ' => 'D',
    'Ƌ' => 'D',
    'ƌ' => 'd',
    'Ƒ' => 'F',
    'ƒ' => 'f',
    'Ɠ' => 'G',
    'Ɨ' => 'I',
    'Ƙ' => 'K',
    'ƙ' => 'k',
    'ƚ' => 'l',
    'Ɲ' => 'N',
    'ƞ' => 'n',
    'Ɵ' => 'O',
    'Ơ' => 'O',
    'ơ' => 'o',
    'Ƥ' => 'P',
    'ƥ' => 'p',
    'ƫ' => 't',
    'Ƭ' => 'T',
    'ƭ' => 't',
    'Ʈ' => 'T',
    'Ư' => 'U',
    'ư' => 'u',
    'Ʋ' => 'V',
    'Ƴ' => 'Y',
    'ƴ' => 'y',
    'Ƶ' => 'Z',
    'ƶ' => 'z',
    'ǅ' => 'D',
    'ǈ' => 'L',
    'ǋ' => 'N',
    'Ǎ' => 'A',
    'ǎ' => 'a',
    'Ǐ' => 'I',
    'ǐ' => 'i',
    'Ǒ' => 'O',
    'ǒ' => 'o',
    'Ǔ' => 'U',
    'ǔ' => 'u',
    'Ǖ' => 'U',
    'ǖ' => 'u',
    'Ǘ' => 'U',
    'ǘ' => 'u',
    'Ǚ' => 'U',
    'ǚ' => 'u',
    'Ǜ' => 'U',
    'ǜ' => 'u',
    'Ǟ' => 'A',
    'ǟ' => 'a',
    'Ǡ' => 'A',
    'ǡ' => 'a',
    'Ǥ' => 'G',
    'ǥ' => 'g',
    'Ǧ' => 'G',
    'ǧ' => 'g',
    'Ǩ' => 'K',
    'ǩ' => 'k',
    'Ǫ' => 'O',
    'ǫ' => 'o',
    'Ǭ' => 'O',
    'ǭ' => 'o',
    'ǰ' => 'j',
    'ǲ' => 'D',
    'Ǵ' => 'G',
    'ǵ' => 'g',
    'Ǹ' => 'N',
    'ǹ' => 'n',
    'Ǻ' => 'A',
    'ǻ' => 'a',
    'Ǿ' => 'O',
    'ǿ' => 'o',
    'Ȁ' => 'A',
    'ȁ' => 'a',
    'Ȃ' => 'A',
    'ȃ' => 'a',
    'Ȅ' => 'E',
    'ȅ' => 'e',
    'Ȇ' => 'E',
    'ȇ' => 'e',
    'Ȉ' => 'I',
    'ȉ' => 'i',
    'Ȋ' => 'I',
    'ȋ' => 'i',
    'Ȍ' => 'O',
    'ȍ' => 'o',
    'Ȏ' => 'O',
    'ȏ' => 'o',
    'Ȑ' => 'R',
    'ȑ' => 'r',
    'Ȓ' => 'R',
    'ȓ' => 'r',
    'Ȕ' => 'U',
    'ȕ' => 'u',
    'Ȗ' => 'U',
    'ȗ' => 'u',
    'Ș' => 'S',
    'ș' => 's',
    'Ț' => 'T',
    'ț' => 't',
    'Ȟ' => 'H',
    'ȟ' => 'h',
    'Ƞ' => 'N',
    'ȡ' => 'd',
    'Ȥ' => 'Z',
    'ȥ' => 'z',
    'Ȧ' => 'A',
    'ȧ' => 'a',
    'Ȩ' => 'E',
    'ȩ' => 'e',
    'Ȫ' => 'O',
    'ȫ' => 'o',
    'Ȭ' => 'O',
    'ȭ' => 'o',
    'Ȯ' => 'O',
    'ȯ' => 'o',
    'Ȱ' => 'O',
    'ȱ' => 'o',
    'Ȳ' => 'Y',
    'ȳ' => 'y',
    'ȴ' => 'l',
    'ȵ' => 'n',
    'ȶ' => 't',
    'ȷ' => 'j',
    'Ⱥ' => 'A',
    'Ȼ' => 'C',
    'ȼ' => 'c',
    'Ƚ' => 'L',
    'Ⱦ' => 'T',
    'ȿ' => 's',
    'ɀ' => 'z',
    'Ƀ' => 'B',
    'Ʉ' => 'U',
    'Ɇ' => 'E',
    'ɇ' => 'e',
    'Ɉ' => 'J',
    'ɉ' => 'j',
    'ɋ' => 'q',
    'Ɍ' => 'R',
    'ɍ' => 'r',
    'Ɏ' => 'Y',
    'ɏ' => 'y',
    'ɓ' => 'b',
    'ɕ' => 'c',
    'ɖ' => 'd',
    'ɗ' => 'd',
    'ɟ' => 'j',
    'ɠ' => 'g',
    'ɦ' => 'h',
    'ɨ' => 'i',
    'ɫ' => 'l',
    'ɬ' => 'l',
    'ɭ' => 'l',
    'ɱ' => 'm',
    'ɲ' => 'n',
    'ɳ' => 'n',
    'ɵ' => 'o',
    'ɼ' => 'r',
    'ɽ' => 'r',
    'ɾ' => 'r',
    'ʂ' => 's',
    'ʄ' => 'j',
    'ʈ' => 't',
    'ʉ' => 'u',
    'ʋ' => 'v',
    'ʐ' => 'z',
    'ʑ' => 'z',
    'ʝ' => 'j',
    'ʠ' => 'q',
    'ͣ' => 'a',
    'ͤ' => 'e',
    'ͥ' => 'i',
    'ͦ' => 'o',
    'ͧ' => 'u',
    'ͨ' => 'c',
    'ͩ' => 'd',
    'ͪ' => 'h',
    'ͫ' => 'm',
    'ͬ' => 'r',
    'ͭ' => 't',
    'ͮ' => 'v',
    'ͯ' => 'x',
    'ᵢ' => 'i',
    'ᵣ' => 'r',
    'ᵤ' => 'u',
    'ᵥ' => 'v',
    'ᵬ' => 'b',
    'ᵭ' => 'd',
    'ᵮ' => 'f',
    'ᵯ' => 'm',
    'ᵰ' => 'n',
    'ᵱ' => 'p',
    'ᵲ' => 'r',
    'ᵳ' => 'r',
    'ᵴ' => 's',
    'ᵵ' => 't',
    'ᵶ' => 'z',
    'ᵻ' => 'i',
    'ᵽ' => 'p',
    'ᵾ' => 'u',
    'ᶀ' => 'b',
    'ᶁ' => 'd',
    'ᶂ' => 'f',
    'ᶃ' => 'g',
    'ᶄ' => 'k',
    'ᶅ' => 'l',
    'ᶆ' => 'm',
    'ᶇ' => 'n',
    'ᶈ' => 'p',
    'ᶉ' => 'r',
    'ᶊ' => 's',
    'ᶌ' => 'v',
    'ᶍ' => 'x',
    'ᶎ' => 'z',
    'ᶏ' => 'a',
    'ᶑ' => 'd',
    'ᶒ' => 'e',
    'ᶖ' => 'i',
    'ᶙ' => 'u',
    '᷊' => 'r',
    'ᷗ' => 'c',
    'ᷚ' => 'g',
    'ᷜ' => 'k',
    'ᷝ' => 'l',
    'ᷠ' => 'n',
    'ᷣ' => 'r',
    'ᷤ' => 's',
    'ᷦ' => 'z',
    'Ḁ' => 'A',
    'ḁ' => 'a',
    'Ḃ' => 'B',
    'ḃ' => 'b',
    'Ḅ' => 'B',
    'ḅ' => 'b',
    'Ḇ' => 'B',
    'ḇ' => 'b',
    'Ḉ' => 'C',
    'ḉ' => 'c',
    'Ḋ' => 'D',
    'ḋ' => 'd',
    'Ḍ' => 'D',
    'ḍ' => 'd',
    'Ḏ' => 'D',
    'ḏ' => 'd',
    'Ḑ' => 'D',
    'ḑ' => 'd',
    'Ḓ' => 'D',
    'ḓ' => 'd',
    'Ḕ' => 'E',
    'ḕ' => 'e',
    'Ḗ' => 'E',
    'ḗ' => 'e',
    'Ḙ' => 'E',
    'ḙ' => 'e',
    'Ḛ' => 'E',
    'ḛ' => 'e',
    'Ḝ' => 'E',
    'ḝ' => 'e',
    'Ḟ' => 'F',
    'ḟ' => 'f',
    'Ḡ' => 'G',
    'ḡ' => 'g',
    'Ḣ' => 'H',
    'ḣ' => 'h',
    'Ḥ' => 'H',
    'ḥ' => 'h',
    'Ḧ' => 'H',
    'ḧ' => 'h',
    'Ḩ' => 'H',
    'ḩ' => 'h',
    'Ḫ' => 'H',
    'ḫ' => 'h',
    'Ḭ' => 'I',
    'ḭ' => 'i',
    'Ḯ' => 'I',
    'ḯ' => 'i',
    'Ḱ' => 'K',
    'ḱ' => 'k',
    'Ḳ' => 'K',
    'ḳ' => 'k',
    'Ḵ' => 'K',
    'ḵ' => 'k',
    'Ḷ' => 'L',
    'ḷ' => 'l',
    'Ḹ' => 'L',
    'ḹ' => 'l',
    'Ḻ' => 'L',
    'ḻ' => 'l',
    'Ḽ' => 'L',
    'ḽ' => 'l',
    'Ḿ' => 'M',
    'ḿ' => 'm',
    'Ṁ' => 'M',
    'ṁ' => 'm',
    'Ṃ' => 'M',
    'ṃ' => 'm',
    'Ṅ' => 'N',
    'ṅ' => 'n',
    'Ṇ' => 'N',
    'ṇ' => 'n',
    'Ṉ' => 'N',
    'ṉ' => 'n',
    'Ṋ' => 'N',
    'ṋ' => 'n',
    'Ṍ' => 'O',
    'ṍ' => 'o',
    'Ṏ' => 'O',
    'ṏ' => 'o',
    'Ṑ' => 'O',
    'ṑ' => 'o',
    'Ṓ' => 'O',
    'ṓ' => 'o',
    'Ṕ' => 'P',
    'ṕ' => 'p',
    'Ṗ' => 'P',
    'ṗ' => 'p',
    'Ṙ' => 'R',
    'ṙ' => 'r',
    'Ṛ' => 'R',
    'ṛ' => 'r',
    'Ṝ' => 'R',
    'ṝ' => 'r',
    'Ṟ' => 'R',
    'ṟ' => 'r',
    'Ṡ' => 'S',
    'ṡ' => 's',
    'Ṣ' => 'S',
    'ṣ' => 's',
    'Ṥ' => 'S',
    'ṥ' => 's',
    'Ṧ' => 'S',
    'ṧ' => 's',
    'Ṩ' => 'S',
    'ṩ' => 's',
    'Ṫ' => 'T',
    'ṫ' => 't',
    'Ṭ' => 'T',
    'ṭ' => 't',
    'Ṯ' => 'T',
    'ṯ' => 't',
    'Ṱ' => 'T',
    'ṱ' => 't',
    'Ṳ' => 'U',
    'ṳ' => 'u',
    'Ṵ' => 'U',
    'ṵ' => 'u',
    'Ṷ' => 'U',
    'ṷ' => 'u',
    'Ṹ' => 'U',
    'ṹ' => 'u',
    'Ṻ' => 'U',
    'ṻ' => 'u',
    'Ṽ' => 'V',
    'ṽ' => 'v',
    'Ṿ' => 'V',
    'ṿ' => 'v',
    'Ẁ' => 'W',
    'ẁ' => 'w',
    'Ẃ' => 'W',
    'ẃ' => 'w',
    'Ẅ' => 'W',
    'ẅ' => 'w',
    'Ẇ' => 'W',
    'ẇ' => 'w',
    'Ẉ' => 'W',
    'ẉ' => 'w',
    'Ẋ' => 'X',
    'ẋ' => 'x',
    'Ẍ' => 'X',
    'ẍ' => 'x',
    'Ẏ' => 'Y',
    'ẏ' => 'y',
    'Ẑ' => 'Z',
    'ẑ' => 'z',
    'Ẓ' => 'Z',
    'ẓ' => 'z',
    'Ẕ' => 'Z',
    'ẕ' => 'z',
    'ẖ' => 'h',
    'ẗ' => 't',
    'ẘ' => 'w',
    'ẙ' => 'y',
    'ẚ' => 'a',
    'Ạ' => 'A',
    'ạ' => 'a',
    'Ả' => 'A',
    'ả' => 'a',
    'Ấ' => 'A',
    'ấ' => 'a',
    'Ầ' => 'A',
    'ầ' => 'a',
    'Ẩ' => 'A',
    'ẩ' => 'a',
    'Ẫ' => 'A',
    'ẫ' => 'a',
    'Ậ' => 'A',
    'ậ' => 'a',
    'Ắ' => 'A',
    'ắ' => 'a',
    'Ằ' => 'A',
    'ằ' => 'a',
    'Ẳ' => 'A',
    'ẳ' => 'a',
    'Ẵ' => 'A',
    'ẵ' => 'a',
    'Ặ' => 'A',
    'ặ' => 'a',
    'Ẹ' => 'E',
    'ẹ' => 'e',
    'Ẻ' => 'E',
    'ẻ' => 'e',
    'Ẽ' => 'E',
    'ẽ' => 'e',
    'Ế' => 'E',
    'ế' => 'e',
    'Ề' => 'E',
    'ề' => 'e',
    'Ể' => 'E',
    'ể' => 'e',
    'Ễ' => 'E',
    'ễ' => 'e',
    'Ệ' => 'E',
    'ệ' => 'e',
    'Ỉ' => 'I',
    'ỉ' => 'i',
    'Ị' => 'I',
    'ị' => 'i',
    'Ọ' => 'O',
    'ọ' => 'o',
    'Ỏ' => 'O',
    'ỏ' => 'o',
    'Ố' => 'O',
    'ố' => 'o',
    'Ồ' => 'O',
    'ồ' => 'o',
    'Ổ' => 'O',
    'ổ' => 'o',
    'Ỗ' => 'O',
    'ỗ' => 'o',
    'Ộ' => 'O',
    'ộ' => 'o',
    'Ớ' => 'O',
    'ớ' => 'o',
    'Ờ' => 'O',
    'ờ' => 'o',
    'Ở' => 'O',
    'ở' => 'o',
    'Ỡ' => 'O',
    'ỡ' => 'o',
    'Ợ' => 'O',
    'ợ' => 'o',
    'Ụ' => 'U',
    'ụ' => 'u',
    'Ủ' => 'U',
    'ủ' => 'u',
    'Ứ' => 'U',
    'ứ' => 'u',
    'Ừ' => 'U',
    'ừ' => 'u',
    'Ử' => 'U',
    'ử' => 'u',
    'Ữ' => 'U',
    'ữ' => 'u',
    'Ự' => 'U',
    'ự' => 'u',
    'Ỳ' => 'Y',
    'ỳ' => 'y',
    'Ỵ' => 'Y',
    'ỵ' => 'y',
    'Ỷ' => 'Y',
    'ỷ' => 'y',
    'Ỹ' => 'Y',
    'ỹ' => 'y',
    'Ỿ' => 'Y',
    'ỿ' => 'y',
    'ⁱ' => 'i',
    'ⁿ' => 'n',
    'ₐ' => 'a',
    'ₑ' => 'e',
    'ₒ' => 'o',
    'ₓ' => 'x',
    '⒜' => 'a',
    '⒝' => 'b',
    '⒞' => 'c',
    '⒟' => 'd',
    '⒠' => 'e',
    '⒡' => 'f',
    '⒢' => 'g',
    '⒣' => 'h',
    '⒤' => 'i',
    '⒥' => 'j',
    '⒦' => 'k',
    '⒧' => 'l',
    '⒨' => 'm',
    '⒩' => 'n',
    '⒪' => 'o',
    '⒫' => 'p',
    '⒬' => 'q',
    '⒭' => 'r',
    '⒮' => 's',
    '⒯' => 't',
    '⒰' => 'u',
    '⒱' => 'v',
    '⒲' => 'w',
    '⒳' => 'x',
    '⒴' => 'y',
    '⒵' => 'z',
    'Ⓐ' => 'A',
    'Ⓑ' => 'B',
    'Ⓒ' => 'C',
    'Ⓓ' => 'D',
    'Ⓔ' => 'E',
    'Ⓕ' => 'F',
    'Ⓖ' => 'G',
    'Ⓗ' => 'H',
    'Ⓘ' => 'I',
    'Ⓙ' => 'J',
    'Ⓚ' => 'K',
    'Ⓛ' => 'L',
    'Ⓜ' => 'M',
    'Ⓝ' => 'N',
    'Ⓞ' => 'O',
    'Ⓟ' => 'P',
    'Ⓠ' => 'Q',
    'Ⓡ' => 'R',
    'Ⓢ' => 'S',
    'Ⓣ' => 'T',
    'Ⓤ' => 'U',
    'Ⓥ' => 'V',
    'Ⓦ' => 'W',
    'Ⓧ' => 'X',
    'Ⓨ' => 'Y',
    'Ⓩ' => 'Z',
    'ⓐ' => 'a',
    'ⓑ' => 'b',
    'ⓒ' => 'c',
    'ⓓ' => 'd',
    'ⓔ' => 'e',
    'ⓕ' => 'f',
    'ⓖ' => 'g',
    'ⓗ' => 'h',
    'ⓘ' => 'i',
    'ⓙ' => 'j',
    'ⓚ' => 'k',
    'ⓛ' => 'l',
    'ⓜ' => 'm',
    'ⓝ' => 'n',
    'ⓞ' => 'o',
    'ⓟ' => 'p',
    'ⓠ' => 'q',
    'ⓡ' => 'r',
    'ⓢ' => 's',
    'ⓣ' => 't',
    'ⓤ' => 'u',
    'ⓥ' => 'v',
    'ⓦ' => 'w',
    'ⓧ' => 'x',
    'ⓨ' => 'y',
    'ⓩ' => 'z',
    'Ⱡ' => 'L',
    'ⱡ' => 'l',
    'Ɫ' => 'L',
    'Ᵽ' => 'P',
    'Ɽ' => 'R',
    'ⱥ' => 'a',
    'ⱦ' => 't',
    'Ⱨ' => 'H',
    'ⱨ' => 'h',
    'Ⱪ' => 'K',
    'ⱪ' => 'k',
    'Ⱬ' => 'Z',
    'ⱬ' => 'z',
    'Ɱ' => 'M',
    'ⱱ' => 'v',
    'Ⱳ' => 'W',
    'ⱳ' => 'w',
    'ⱴ' => 'v',
    'ⱸ' => 'e',
    'ⱺ' => 'o',
    'ⱼ' => 'j',
    'Ꝁ' => 'K',
    'ꝁ' => 'k',
    'Ꝃ' => 'K',
    'ꝃ' => 'k',
    'Ꝅ' => 'K',
    'ꝅ' => 'k',
    'Ꝉ' => 'L',
    'ꝉ' => 'l',
    'Ꝋ' => 'O',
    'ꝋ' => 'o',
    'Ꝍ' => 'O',
    'ꝍ' => 'o',
    'Ꝑ' => 'P',
    'ꝑ' => 'p',
    'Ꝓ' => 'P',
    'ꝓ' => 'p',
    'Ꝕ' => 'P',
    'ꝕ' => 'p',
    'Ꝗ' => 'Q',
    'ꝗ' => 'q',
    'Ꝙ' => 'Q',
    'ꝙ' => 'q',
    'Ꝛ' => 'R',
    'ꝛ' => 'r',
    'Ꝟ' => 'V',
    'ꝟ' => 'v',
    'Ａ' => 'A',
    'Ｂ' => 'B',
    'Ｃ' => 'C',
    'Ｄ' => 'D',
    'Ｅ' => 'E',
    'Ｆ' => 'F',
    'Ｇ' => 'G',
    'Ｈ' => 'H',
    'Ｉ' => 'I',
    'Ｊ' => 'J',
    'Ｋ' => 'K',
    'Ｌ' => 'L',
    'Ｍ' => 'M',
    'Ｎ' => 'N',
    'Ｏ' => 'O',
    'Ｐ' => 'P',
    'Ｑ' => 'Q',
    'Ｒ' => 'R',
    'Ｓ' => 'S',
    'Ｔ' => 'T',
    'Ｕ' => 'U',
    'Ｖ' => 'V',
    'Ｗ' => 'W',
    'Ｘ' => 'X',
    'Ｙ' => 'Y',
    'Ｚ' => 'Z',
    'ａ' => 'a',
    'ｂ' => 'b',
    'ｃ' => 'c',
    'ｄ' => 'd',
    'ｅ' => 'e',
    'ｆ' => 'f',
    'ｇ' => 'g',
    'ｈ' => 'h',
    'ｉ' => 'i',
    'ｊ' => 'j',
    'ｋ' => 'k',
    'ｌ' => 'l',
    'ｍ' => 'm',
    'ｎ' => 'n',
    'ｏ' => 'o',
    'ｐ' => 'p',
    'ｑ' => 'q',
    'ｒ' => 'r',
    'ｓ' => 's',
    'ｔ' => 't',
    'ｕ' => 'u',
    'ｖ' => 'v',
    'ｗ' => 'w',
    'ｘ' => 'x',
    'ｙ' => 'y',
    'ｚ' => 'z',
    '1' => 'a',
    '2' => 'b',
    '3' => 'c',
    '4' => 'd',
    '5' => 'e',
    '6' => 'f',
    '7' => 'g',
    '8' => 'h',
    '9' => 'i',
    '0' => 'j',
  );
  return strtr($text, $trans);
}
